basePath: /
definitions:
  app.Response:
    properties:
      code:
        type: integer
      data:
        type: object
      msg:
        type: string
    type: object
  c_index.LoginForm:
    properties:
      password:
        type: string
      username:
        type: string
    type: object
  c_user.AddUserForm:
    properties:
      email:
        type: string
      idCard:
        type: string
      mobile:
        type: string
      name:
        type: string
      sex:
        type: integer
      username:
        type: string
    type: object
  c_user.AuthForm:
    properties:
      password:
        type: string
      username:
        type: string
    type: object
  c_user.EditUserForm:
    properties:
      city:
        type: string
      deptId:
        type: integer
      district:
        type: string
      email:
        type: string
      hobby:
        type: string
      id:
        type: integer
      idCard:
        type: string
      liveAddress:
        type: string
      mobile:
        type: string
      name:
        type: string
      picId:
        type: integer
      province:
        type: string
      remarks:
        type: string
      sex:
        type: integer
      status:
        type: integer
      username:
        type: string
    type: object
  c_user.ListUserForm:
    properties:
      idCard:
        type: string
      name:
        type: string
      username:
        type: string
    type: object
host: 127.0.0.1:8090
info:
  contact:
    email: support@swagger.io
    name: API 接口
    url: http://www.swagger.io/support
  description: This is a api server for project whacos .
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Swagger For Project Whacos
  version: "1.0"
paths:
  /app/user/get/{id}:
    get:
      consumes:
      - application/json
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: string
      - description: token
        in: query
        name: token
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
            type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/app.Response'
            type: object
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/app.Response'
            type: object
      summary: 按ID 获取用户
      tags:
      - APP相关
  /auth:
    post:
      consumes:
      - application/json
      description: 通过 username 和 password 获取 token
      parameters:
      - description: authForm
        in: body
        name: auth
        required: true
        schema:
          $ref: '#/definitions/c_user.AuthForm'
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
            type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/app.Response'
            type: object
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/app.Response'
            type: object
      summary: 校验用户并获取token 值
      tags:
      - DEFAULT
  /index:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
            type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/app.Response'
            type: object
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/app.Response'
            type: object
      summary: 跳转到首页
      tags:
      - DEFAULT
  /login:
    post:
      consumes:
      - application/json
      parameters:
      - description: loginForm
        in: body
        name: login
        required: true
        schema:
          $ref: '#/definitions/c_index.LoginForm'
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
            type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/app.Response'
            type: object
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/app.Response'
            type: object
      summary: 用户登录
      tags:
      - DEFAULT
  /sys/user/add:
    post:
      consumes:
      - application/json
      parameters:
      - description: addUserForm
        in: body
        name: addUser
        required: true
        schema:
          $ref: '#/definitions/c_user.AddUserForm'
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
            type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/app.Response'
            type: object
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/app.Response'
            type: object
      summary: 新增用户
      tags:
      - 系统用户相关
  /sys/user/edit:
    put:
      consumes:
      - application/json
      parameters:
      - description: editUserForm
        in: body
        name: editUser
        required: true
        schema:
          $ref: '#/definitions/c_user.EditUserForm'
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
            type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/app.Response'
            type: object
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/app.Response'
            type: object
      summary: 修改用户信息
      tags:
      - 系统用户相关
  /sys/user/get/{id}:
    get:
      consumes:
      - application/json
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
            type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/app.Response'
            type: object
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/app.Response'
            type: object
      summary: 按ID 获取用户
      tags:
      - 系统用户相关
  /sys/user/list:
    post:
      consumes:
      - application/json
      parameters:
      - description: listUserForm
        in: body
        name: listUser
        required: true
        schema:
          $ref: '#/definitions/c_user.ListUserForm'
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
            type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/app.Response'
            type: object
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/app.Response'
            type: object
      summary: 查询用户列表
      tags:
      - 系统用户相关
  /sys/user/remove/{id}:
    delete:
      consumes:
      - application/json
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
            type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/app.Response'
            type: object
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/app.Response'
            type: object
      summary: 移除指定用户
      tags:
      - 系统用户相关
swagger: "2.0"
